# Generated by Django 3.1.4 on 2020-12-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20201218_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default='', upload_to='image_upload'),
            preserve_default=False,
        ),
    ]
