# Generated by Django 3.1.4 on 2020-12-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20201217_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='fax_number',
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.IntegerField(default=1),
        ),
    ]
